services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: database
      POSTGRES_PASSWORD: localtest
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/timescale:/var/lib/postgresql/data/pgdata
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
