services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: jskdlajdakld
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/timescale:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U db" ]
      interval: 5s
      timeout: 5s
      retries: 5

    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  db-migrations:
    image: derzwerggimli/rogue.hub.v2.migrations:latest
    environment:
      DATABASE_URL: postgres://db:jskdlajdakld@timescaledb:5432/datahub
    depends_on:
      timescaledb:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  api:
    image: derzwerggimli/rogue.hub.v2.api:latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://db:jskdlajdakld@timescaledb:5432/datahub
      API_HOST: 127.0.0.1
      API_PORT: 3000
      RUST_LOG: info
    depends_on:
      timescaledb:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  indexer_marketplace:
    image: derzwerggimli/rogue.hub.v2.indexer:latest
    environment:
      RPC_URL: "https://rpc.ironforge.network/mainnet?apiKey=01JWX6ZJC433RA3FG6C3WCZMEC"
      DATABASE_URL: "postgres://db:jskdlajdakld@timescaledb:5432/datahub"
      INDEXER_NAME: marketplace_new
    depends_on:
      timescaledb:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  processor_marketplace:
    image: derzwerggimli/rogue.hub.v2.decoder:latest
    environment:
      RPC_URL: "https://rpc.ironforge.network/mainnet?apiKey=01JWX6ZJC433RA3FG6C3WCZMEC"
      DATABASE_URL: "postgres://db:jskdlajdakld@timescaledb:5432/datahub"
      PROGRAM_ID: traderDnaR5w6Tcoi3NFm53i48FTDNbGjBSZwWXDRrg
    depends_on:
      timescaledb:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "1m"


